name: Deploy to VM

on:
  push:
    branches:
      - main  # Change this if your main branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VM
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          cd ~/car_price_predictor
          git pull origin main
          source venv/bin/activate  # If using a virtual environment
          pip install -r requirements.txt  # Install dependencies
          sudo systemctl restart car_price_predictor.service  # Restart your application
